- name: Install packages
  apt:
    name: 
      - htop
      - mc
      - tmux
      - vim
      - openssh-server
      - xymon-client
      - neofetch
  when: (ansible_facts['os_family'] == "Debian" )

- name: Install packages
  yum:
    name:
      - htop
      - mc
      - tmux
      - vim
      - openssh-server
      - neofetch
  when: (ansible_facts['os_family'] == "RedHat" )


